@extends('home.app')
@section('content')
@include('home.header')

<!--======================= layout ========================-->

<div class="small-layout animatedParent" style="background-image: url('{{URL::asset('livesite/images/banners/1.jpg')}}') ;">
    <div class="mask"></div>
    <h1 class=" header_middle text-center animated bounceInDown slower go">Terms and Conditions</h1>
</div>


<!--=======================================================-->






<!--======================= Questions  ========================-->

<section class="questions-answers container">
            <div class="section-content">
                <div class="question">


               


<p><strong>Thank you for your interest  in Indy John.</strong></p>

Indy John is a virtual marketplace located at <a href="http://www.indyjohn.com">www.indyjohn.com</a> (the "Site") for suppliers and buyers of  industrial equipment, materials and services (the "Service").  The Service is owned, and operated by Indy John,  Inc. ("Indy John," "we," "our," or "us").   The generic terms "you," "your," and "yours" refer to all users of the Service  irrespective of whether offering to sell, selling, browsing or buying industrial  equipment, materials and services (the "Merchandise").  The term "supplier" specifically refers to  users offering to sell their Merchandise, and the term "buyer" specifically  refers to users buying the Merchandise, through the Service.</p>
<p>  IMPORTANT – PLEASE READ CAREFULLY:  THESE INDY JOHN TERMS OF SERVICE CONSISTING  OF THE GENERAL TERMS AND CONDITIONS, SELLING ON INDY JOHN TERMS AND CONDITIONS  AND BUYING ON INDY JOHN TERMS AND CONDITIONS (COLLECTIVELY, THE "TERMS") ALONG  WITH ALL THE RULES, POLICIES AND GUIDELINES INCORPORATED IN THESE TERMS BY  REFERENCE CONSTITUTE A LEGALLY BINDING AGREEMENT BETWEEN INDY JOHN AND YOU  (EITHER AN INDIVIDUAL OR A SINGLE ENTITY) AND GOVERN YOUR USE OF THE SERVICE TO  LIST, SELL, OFFER TO SELL OR PURCHASE THE MERCHANDISE.  BY REGISTERING TO OPEN AN ACCOUNT AND/OR USING  THE SERVICE, YOU (ON BEHALF OF YOURSELF OR THE BUSINESS OR ENTITY YOU  REPRESENT) AGREE AND ACKNOWLEDGE TO BE BOUND BY THESE TERMS.  IF YOU DO NOT AGREE TO BE BOUND BY THESE  TERMS, PLEASE DO NOT USE THE SERVICE.<br>
WE RESERVE THE RIGHT TO MODIFY THESE TERMS AT ANY  TIME, AND EACH SUCH MODIFICATION SHALL BE EFFECTIVE UPON POSTING.  ALL MATERIAL MODIFICATIONS WILL APPLY  PROSPECTIVELY ONLY.  YOU'RE CONTINUED USE  OF THE SERVICE FOLLOWING ANY SUCH MODIFICATION CONSTITUTES YOUR AGREEMENT TO BE  BOUND BY THESE TERMS, AS MODIFIED.  IF  ANY MODIFICATION IS NOT ACCEPTABLE TO YOU, YOUR SOLE REMEDY AND RECOURSE IS TO  DISCONTINUE USE OF THE SERVICE.   THEREFORE, IT IS IMPORTANT FOR YOU TO REVIEW THESE TERMS REGULARLY.</p>
<p><strong>I.  GENERAL TERMS AND CONDITIONS:</strong></p>
  These General Terms and Conditions are a part of the Indy John Terms of  Service and apply to all users of the Service, whether offering to sell,  selling, browsing or buying Merchandise through the Service.
  <p><strong>Eligibility -</strong></p>
  To use the Service, you must be able to enter into a binding contract  under the applicable laws.  If you are an  individual, you represent that you are 18 years of age or over, or of the legal  age to form a binding contract in your jurisdiction if that age is greater than  18 years.  If you are accepting these  Terms on behalf of a company or other legal entity, you represent that you have  the authority to bind such entity to these Terms.<br>
  <p><strong>Registration -</strong></p>
  You are required to register  and create a unique, password-protected account ("your account") in order to  access and use the Service to offer, sell or buy Merchandise.  You agree to: (a) provide true,  accurate, current, and complete information as prompted by the registration  form; and (b) maintain and update such information to keep it true,  accurate, current, and complete at all times.   You authorize us to use any information you provide us (including your  SSN, TIN or EIN) to verify your antecedents and obtain your credit reports  before opening your account.  We reserve  the right to reject your application or delete your account without warning if  you are found to have misrepresented your registration information or you fail  to meet our eligibility criteria.<br>
  You are responsible for  maintaining the confidentiality of your account user name and password.  You agree to (a) immediately notify us of any  unauthorized use of your password or account, or any other breach of security,  and (b) ensure that you exit from your account at the end of each session.  You will be solely responsible for  safeguarding your password and also for any actions under your password and  account, whether authorized by you or not.<br>
  <p><strong>Acceptable Use Policy -</strong></p>
  Subject to your acceptance and compliance with  these Terms, we hereby grant you permission to access and use the Service,  provided that you shall not (and not allow third party to): (i) lead off  the Site to complete transactions in any manner including through links in  emails, chat or phone correspondence with users; (ii) modify, adapt,  translate, or reverse engineer any portion of the Service or the Site; (iii) remove  any copyright, trademark or other proprietary rights notices contained in or on  the Site or Service or in or on any content or other material obtained via the Site  or Service; (iv) use any robot, spider, site search/retrieval application,  or other automated device, process or means to access, retrieve or index any  portion of the Service; (v) access, retrieve or index any portion of the Service  for purposes of constructing or populating a searchable database of business  reviews; (vi) collect or harvest any information about other users or  members (including usernames and/or email addresses) for any purpose; (vii) reformat  or frame any portion of the web pages that are part of the Site; (viii) create  user accounts by automated means or under false or fraudulent pretenses; (ix) create  or transmit unwanted electronic communications such as "spam" to other users or  members of the Service or otherwise interfere with other users' or members'  enjoyment of the Service; (x) transmit any viruses, worms, defects, Trojan  horses or other items of a destructive nature; (xi) use the Service to  violate the security of any computer network, crack passwords or security  encryption codes, transfer or store illegal material, including any material  that may be deemed threatening or obscene; (xii) copy or store any content  offered on the Site for other than your own personal use; (xiii) use any  device, software or routine that interferes with the proper working of the Service,  or otherwise attempt to interfere with the proper working of the Service; (xiv) take  any action that imposes, or may impose in our sole discretion, an unreasonable  or disproportionately large load on our IT infrastructure; (xv) use the Service  intentionally or unintentionally, to violate any applicable local, state,  national or international law; or (xv) collect or store personal data  about other users in connection with the prohibited activities described in  this paragraph.<br>
<p><strong>Indy John Role and Release -</strong></p>
  <p>The Service is an online  marketplace for third-party suppliers and buyers to locate or advertise  Merchandise and Services subject to these Terms.  We are neither a supplier nor a buyer and we  do not manage payments between buyer and supplier.  As a supplier, you may list any permitted  items of Merchandise or Services on the Site and, as a buyer, you may locate  any product or service offered by the suppliers.  Therefore, if you have a dispute with a supplier  or a buyer, you release us, our affiliates (and our respective officers,  directors, agents, subsidiaries, joint ventures and employees) from claims,  demands and damages (actual and consequential) of every kind and nature, known  and unknown, suspected and unsuspected, disclosed and undisclosed, arising out  of, or in any way connected with, such disputes.  In  entering into this release you expressly waive any protections (whether  statutory or otherwise) that would otherwise limit the coverage of this release  to include only those claims which you may know or suspect to exist in your  favor at the time of agreeing to this release.  For example, if you are a California resident,  you waive California Civil Code §1542, which says: "A general release does not  extend to claims which the creditor does not know or suspect to exist in his  favor at the time of executing the release, which if known by him must have  materially affected his settlement with the debtor."</p>
  <p>  We are not responsible in  any way for actual transaction between a supplier and a buyer.  Without limiting the generality of the  foregoing, you acknowledge and agree as follows: (i) we do not participate  in any actual transactions, including, without limitation, negotiations,  discussions, or proposals, and you expressly waive any requirement that  purports to impose on us an obligation to perform any services other than those  expressly undertaken by us; (ii) we do not render legal, brokerage, scientific  or other professional advice or services; in the event you desire or need such  services, we strongly advise you to secure the same; (iii) we are not  undertaking any, and have no, duties to you including, without limitation, the  obligation to screen prospective suppliers or buyers; and (iv) while we  comply with applicable state and federal laws, we cannot guarantee that our  users so comply.  Accordingly, we assume  no liability for any user's failures to comply with such laws.<br>
  </p>
<p><strong>Reservation of Rights-</strong></p>
   You  acknowledge that the Site, the Service and the underlying software and all  intellectual property rights therein, including copyrights, patent rights,  trade secret rights, and trademark rights, are owned by us.  All rights not expressly granted herein are  reserved by us.  Except as expressly and  specifically set forth in the Terms, nothing herein shall be construed as  granting to you any property right, by license, implication, estoppel, or  otherwise, to any of our intellectual property rights.<br>
  Indy John and its associated  logos are either registered trademarks or trademarks of ours.  All other company names, logos and other  identifying marks that may be listed as part of our Service may be trademarks  of their respective owners.  WE DO NOT  CLAIM ANY OWNERSHIP IN ANY THIRD PARTY'S TRADEMARKS NOR DO WE CLAIM ANY  SPONSORSHIP, ASSOCIATION WITH OR ENDORSEMENT BY SUCH THIRD PARTIES.<br>
  <p><strong>Your Content -</strong></p>
  <p>We may allow you to post  reviews, comments, photos, and other content; send communications; and submit  suggestions, ideas, comments, questions, or other information ("your content")  on the Site.  You are solely responsible  for your content.  Subject to the  licenses you are granting hereunder, you retain all right, title and interest,  including without limitation all worldwide intellectual property rights, in and  to your content.  </p>
  <p>  By submitting, posting or  displaying your content on or through the Site, you automatically grant to us a  worldwide, perpetual, royalty-free, irrevocable, non-exclusive, sub-licensable  and transferable right and license to use, reproduce, store, host, index,  cache, distribute (through multiple tiers), publicly perform, publicly display,  (each of the foregoing in any form, medium or technology now known or later  developed), modify and adapt including without limitation the right to adapt  for streaming, downloading, broadcasting, distribution, publicly displaying,  publicly performing (each of the foregoing in any form, medium or technology  now known or later developed), create derivative works from, and exercise all  aforesaid rights with respect to such derivative works, and otherwise exploit  in any manner, your content or any part thereof.  You hereby expressly waive any and all  so-called moral rights you may have in your content.</p>
  <p>  You hereby represent and  warrant that your content, (i) and our use thereof pursuant to these Terms  does not and will not, directly or indirectly, violate, infringe or breach any  duty toward or rights of any person or entity, including without limitation any  copyright, trademark, service mark, trade secret, other intellectual property,  publicity or privacy right, (ii) does not contain any material that is  sexual, pornographic, erotic, obscene, indecent or profane in its use of sexual  language or description or depictions of sexual acts, (iii) is not  fraudulent, misleading, hateful, tortuous, defamatory, slanderous, libelous,  abusive, violent, threatening, profane, vulgar or obscene, (iv) does not  harass others, promote bigotry, racism, hatred or harm against any individual  or group, promote discrimination based on race, sex, religion, nationality,  sexual orientation or age, or otherwise interfere with another party's use of  the Service, (v) does not promote illegal or harmful activities or  substances or provide instructional information about activities such as making  or buying illegal weapons or substances, (vi) is not illegal, unlawful or  contrary to the laws or regulations in any state or country where, as  applicable, your content are created, displayed or accessed, (vii) does  not contain any adware, malware, spyware, computer programming routines,  software or viruses that are intended to damage, interfere with or in any way  limit the functionality of any computer software or hardware or  telecommunications equipment, intercept or expropriate any system data or  personal information, permit unauthorized access to the Service or any part  thereof or disable, damage or erase any portion of the content or  advertisements processed or stored therein; or (viii) does not constitute  unsolicited bulk email, junk mail, spam or chain letters.<br>
  </p>
  <p><strong>Merchandise -</strong></p>
  You are only allowed to list, advertise, and  promote Merchandise and Services through our Service.  We reserve the right to determine whether  your products or services qualify for offering through the Service.  Without limiting the foregoing, following  products are expressly prohibited from being listed through the Service: (a) offensive  materials, including material that incites racial hatred or promotes  discrimination based on race, sex, religion, national origin, physical ability,  sexual orientation or age; (b) obscene materials including pornographic  material; (c) live animals; (d) intoxicating liquor and tobacco and  home-made alcoholic beverages; (e) firearms and ammunition; (f) stolen  goods; (g) advertisements; (h) illegal or prescription drugs; (i) items  whose sale, distribution or offering for sale is prohibited by any applicable  law; (j) offensive weapons, poisons and dangerous substances (as defined  by the applicable law or laws).<br>
<p><strong>Disclaimer of Warranties -</strong></p>
  <p>THE SITE, THE SERVICE  AND ALL FEATURES AND FUNCTIONALITIES ASSOCIATED THEREWITH ARE PROVIDED "AS IS"  AND "AS AVAILABLE" WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND.  YOU EXPRESSLY AGREE THAT YOUR USE OF THE SERVICE  IS AT YOUR SOLE DISCRETION AND RISK.  YOU  ACKNOWLEDGE AND AGREE THAT YOU MUST EVALUATE, AND BEAR ALL RISKS ASSOCIATED  WITH THE USE OF THE SERVICE AND PURCHASE AND SALE OF MERCHANDISE, AND ANY  CONTENT DESCRIBING THE MERCHANDISE, INCLUDING ANY RELIANCE ON THE ACCURACY,  COMPLETENESS, OR USEFULNESS OF SUCH CONTENT.</p>
  <p>  TO THE FULLEST  EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, INCLUDING, BUT NOT LIMITED  TO, THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR PARTICULAR PURPOSE,  NON-INFRINGEMENT AND ANY  IMPLIED WARRANTY ARISING FROM COURSE OF DEALING OR USAGE OF TRADE.  WE DO NOT GUARANTEE, REPRESENT, OR WARRANT  THAT YOUR USE OF THE SERVICE WILL BE UNINTERRUPTED OR ERROR-FREE, AND YOU AGREE  THAT WE MAY ELIMINATE OR OTHERWISE MODIFY ANY OR ALL ASPECTS OF THE SERVICE,  INCLUDING ANY FEATURES THEREOF, WITHOUT COMPENSATION OR NOTICE TO YOU.  WE MAKE NO WARRANTIES ABOUT THE ACCURACY,  RELIABILITY, COMPLETENESS, OR TIMELINESS OF THE SERVICE OR THAT YOUR USE OF THE  SERVICE WILL BE FREE FROM INTERRUPTION, LOSS, CORRUPTION, ATTACK, VIRUSES,  INTERFERENCE, HACKING, OR OTHER SECURITY INTRUSION AND WE DISCLAIM ANY  LIABILITY WITH RESPECT THERETO.<br>
  </p>
  <p><strong>Limitation of Liability -</strong></p>
  You understand and agree that your use of the  Marketplace is at your own discretion and risk and that you will be solely  responsible for any damages that arise from such use including, without  limitation, for loss of data and or any type of malfunction to your computer.  IN NO EVENT SHALL WE OR ANY OF OUR  SHAREHOLDERS, DIRECTORS, OFFICERS OR EMPLOYEES BE LIABLE (JOINTLY OR SEVERALLY)  TO YOU FOR PERSONAL INJURY OR ANY SPECIAL, INCIDENTAL, INDIRECT OR  CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS  OF USE, DATA OR PROFITS, BUSINESS INTERRUPTION OR ANY OTHER COMMERCIAL DAMAGES  OR LOSS, WHETHER OR NOT ADVISED OF THE POSSIBILITY OF DAMAGE, AND ON ANY THEORY  OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OR PERFORMANCE OF  THE SERVICE.  IN NO EVENT SHALL OUR TOTAL  LIABILITY TO YOU OR ANY THIRD PARTY IN ANY CIRCUMSTANCE FOR LOSSES ARISING FROM  THE USE OR INABILITY TO USE THE SERVICE (OTHER THAN AS MAY BE REQUIRED BY  APPLICABLE LAW IN CASES INVOLVING PERSONAL INJURY) EXCEED THE COMMISSION EARNED  BY US FROM THE TRANSACTION GIVING RISE TO THE CLAIM.  THE FOREGOING LIMITATIONS WILL APPLY EVEN IF  THE ABOVE STATED REMEDY FAILS OF ITS ESSENTIAL PURPOSE.  SOME JURISDICTIONS DO NOT ALLOW THE  LIMITATION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES SO SOME OF THE  ABOVE LIMITATIONS MAY NOT APPLY TO YOU.<br>
  <p><strong>Indemnification -</strong></p>
  You will defend, indemnify and hold harmless us  and our affiliates (and their respective employees, directors, agents and  representatives) from and against any and all claims, costs, losses, damages,  judgments, penalties, interest and expenses (including reasonable attorneys'  fees) arising out of any claim that arises out of or relates to: (i) any actual  or alleged breach of your representations, warranties, or obligations set forth  in these Terms; or (ii) your use of the Service.<br>
  <p><strong>Basis of the Bargain -</strong></p>
  THE PARTIES ACKNOWLEDGE AND  AGREE THAT THE FOREGOING SECTIONS ON INDEMNIFICATION, WARRANTY DISCLAIMER AND  LIMITATION OF LIABILITY FAIRLY ALLOCATE THE RISKS BETWEEN THE PARTIES AND ARE  ESSENTIAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN THE PARTIES.<br>
<p><strong>Privacy -</strong></p>
  <p>All information we collect on the Site is subject  to our Privacy Policy located in IndyJohn.com privacy policy page.  By using the Service, you consent to all  actions taken by us with respect to your information in compliance with the  Privacy Policy.  We reserve the right to  send notifications and updates about the Service and as a user of the Service,  you can opt out of receiving such messages in accordance with the Privacy Policy.</p>
  <p>
  You will not, and will cause your affiliates not  to, directly or indirectly disclose, convey or use any order information or  other data or personal information acquired by you or your affiliates from us  as a result of your use of the Service or the transactions contemplated hereby,  except as necessary for you to perform your obligations, provided that you  ensure that every recipient uses the information only for that purpose and  complies with the restrictions applicable to you related to that information.</p>
  <p><strong>Anonymous Data Collection</strong><strong>-</strong></p>
  We shall  have the right to utilize data capture, syndication, analysis tools, and other  similar tools to extract, compile, synthesize, and analyze any non-personally  identifiable data or information resulting from your use of the Service ("anonymous  data").  To the extent that any anonymous  data is collected by us, such data shall be solely owned by us and may be used  by us for any lawful business purpose without a duty of accounting to you  therefor; provided, that the anonymous data is used only in an aggregated form,  without specifically identifying the source of the anonymous data.<br>
  <p><strong>Use of Third Party Services -</strong></p>
  Indy John does allow users  to engage and interact using third party services within the Indy John platform,  mainly social media applications. Third party service icons may appear on our  platform but this doesn't signify any partnership or business connection.  We are not an official partner of any third  party service company and all users of these applications should have a clear  understanding of this prior to using our service. All third party terms of use,  as well as privacy policies should be clearly understood prior to using this  platform.<br>
  <p><strong>General -</strong></p>
  These Terms shall be governed by and construed in  accordance with the laws of the State of California, excluding its conflicts of  laws principles.  The United Nations  Convention on Contracts for the International Sale of Products is excluded and  does not apply to these Terms.  If any  dispute relating in any way to these Terms or the policies or your use of the Service  shall be submitted to confidential arbitration in Los Angeles County,  California, USA, except that, to the extent you have in any manner violated or  threatened to violate our intellectual property rights, we may seek injunctive  or other appropriate relief in any state or federal court in the State of  California, USA and you consent to exclusive jurisdiction and venue in such  courts.  Arbitration under these Terms  shall be administered by JAMS pursuant to its Streamlined Arbitration Rules and  Procedures.  The arbitrator's award shall  be binding and may be entered as a judgment in any court of competent jurisdiction.  To the fullest extent permitted by applicable  law, no arbitration under these Terms shall be joined to an arbitration  involving any other party subject to these Terms, whether through class  arbitration proceedings or otherwise.   The failure to require performance of any provision shall not affect our  right to require performance at any time thereafter, nor shall a waiver of any  breach or default of these Terms constitute a waiver of any subsequent breach  or default or a waiver of the provision itself.   If any portion of these Terms is found to be unenforceable, such portion  will be modified to reflect the parties' intention and only to the extent  necessary to make it enforceable, and the remaining provisions of these Terms  will remain in full force and effect.   These Terms constitute the entire and exclusive understanding and  agreement between you and us regarding this subject matter, and supersedes any  and all prior or contemporaneous agreements or understandings, written and  oral.<br>
  <p><strong>Promotions and Giveaways -</strong></p>
  All  promotions, special offers, discounted prices, and all other marketed or  solicited information from Indy John, Inc. are valid for whatever the offer  claims but are also subject to change or be withdrawn at any time without prior  warnings.  If you do not agree with these  terms, stop using our service and we will remove your account upon written  request.</p>
<p>
<p><strong>II.   SUPPLYING ON INDY JOHN TERMS AND CONDITIONS</strong></p>
<p>Supplying on Indy John Terms and Conditions are a part of the Indy  John Terms of Service and apply to all suppliers using the Service in addition  to the General Terms and Conditions.</p>
<p><strong>Offering and Listing your  Products and Services -</strong></p>
  After you have set up your  account, we will enable you to create Lead Requests and offer or list your Merchandise  or Service on the Site.  We may enable  you to list your Merchandise on a sub-Site that lists solely your Merchandise,  or lists that specific item of Merchandise. As a supplier, you will be  responsible for providing accurate and complete information and for promptly  updating that information, as necessary, to ensure it at all times remains  accurate and complete.  Your listing on  the Site constitutes an offer to buy your Merchandise, subject to the terms and  conditions contained herein or such other terms and conditions as you may agree  with a buyer.<br>
<p><strong>Team Supplying -</strong></p>
  You agree to all Terms and  Conditions in this section, as well as all others not listed in this section. Indy  John does allow all users to engage in team supplying.  All teams consist of a Team Manager and Team  Members, these team relationships are established when team managers invite or  manually add team members to join their team.   Indy John doesn't have an interest in these relationships and will not  be responsible for ANY disputes resulting from team supplying efforts.  Removal from a team is done by Team Manager  which controls ALL team data, details and members.  Payment of user monthly memberships is the  responsibility of the individual users.   Team Billing is available as an option for group paying.<br>
  <p><strong>Order Processing and Collection of Sales Proceeds -</strong></p>
  We are not currently  managing payments with our service but for each item of your Merchandise sold  through our Service, we will make available to you the Quote Information (as  defined below) received by us.  You agree  that you have exclusive rights to collect all sales proceeds from the buyers including  the applicable shipping, handling and other charges determined by you.  <br>
<p><strong>Transaction and  Fulfillment -</strong></p>
  We are not currently allowing transaction and fulfillment with our  service but upon using our service you agree to: (a) source, offer,  sell and fulfill each order placed by a buyer for your Merchandise, in each  case in accordance with the terms of the applicable Order Information, these Terms,  and all terms provided by you and displayed on the Site at the time of the  order and be solely responsible for and bear all risk for those activities; (b) package  each item of your Merchandise in a commercially reasonable manner (c) include  an order-specific packing slip, and, if applicable, any tax invoices, within  each shipment of your Merchandise; (d) identify yourself as the supplier  of your Merchandise on all packing slips or other information included or  provided in connection with your Merchandise and as the person to which a  customer may return the applicable product
  <p><strong>Cancellations, Returns  and Refunds -</strong></p>
  Indy John is marketplace that matches and connects buyers and suppliers  of merchandise and services.  We do not  manage payments or allow sales to post with our service.  We do not accept returned merchandise.  You agree to post your returns and refunds policy on the Site.  For your Merchandise, you will accept and  process all cancellations, returns, refunds and adjustments in accordance with your  refunds and returns policies displayed on the Site at the time of the order.  You will determine and calculate the amount of  all refunds and adjustments (including any taxes, shipping and handling or  other charges) or other amounts to be paid by you to buyers in connection with  cancelled orders.  You will route all  payments to buyers in connection with cancelled orders through Indy John.  
  <p><strong>Delivery Errors and  Recalls -</strong></p>
  You are solely responsible  for any non-performance, non-delivery, misdelivery, theft or other mistake or  act in connection with the fulfillment of each order for your Merchandise,  except to the extent caused by: our failure to make available to you Order  Information as it was received by us.  You  will notify us promptly as soon as you have knowledge of any public or private  recalls of your Merchandise.<br>
<p><strong>Parity with Your Other  Sales Channels -</strong></p>
  You are free to determine  which of your Merchandise you wish to offer through the Service.  You will maintain parity between the products  you offer through other sales channels you use and the products you list on the  Site by ensuring that : (a) the purchase price and every other term of  offer or sale of your Merchandise (including associated shipping and handling  charges, shipment information, any "low price" guarantee, rebate or discount,  any free or discounted products or other benefit available as a result of  purchasing one or more other products, and terms of applicable cancellation,  return and refund policies) is at least as favorable to the Site users as the  most favorable terms upon which a product is offered or sold via other sales  channels; (b) customer service for your Merchandise is at least as  responsive and available and offers at least the same level of support as the  most favorable customer services offered in connection with any of other sales  channels; and (c) your content, product and service information and other  information regarding your Merchandise that you provide on the Site is of at  least the same level of quality as the highest quality information displayed or  used in other sales channels.  If you  become aware of any non-compliance with (a) above, you will promptly compensate  adversely affected customers by making appropriate refunds to them in  accordance with these Terms.<br>
  <p><strong>Supplier Taxes -</strong></p>
  We are not currently handling payments so you agree that it is your responsibility  to determine whether Supplier Taxes (as defined below) are accurate and apply  to the sales transactions involving your Merchandise and to notify us.  "Supplier Taxes" means any and all sales,  goods and services, use, excise, import, export, value added, consumption and  other taxes and duties assessed, incurred or required to be collected or paid  for any reason in connection with any advertisement, offer or sale of products  by you on or through the Site, or otherwise in connection with any action,  inaction or omission of you or any of affiliate of yours, or any of your or  their respective employees, agents, contractors or representatives.<br>
<p><strong>Reviews and Endorsements  -</strong></p>
  We may use mechanisms that review and endorse, or allow users to review  and endorse, your Merchandise, Service and your performance as a supplier.  We may make these ratings and feedback  publicly available.<br>
<p><strong>Control of Site -</strong></p>
  We have the right in our  sole discretion to determine the content, appearance, design, functionality and  all other aspects of the Site, including by redesigning, modifying, removing or  restricting access to any of them, and by suspending, prohibiting or removing  any listing.<br>
  <p>&nbsp;</p>
  <p><strong>  III.  BUYING ON INDY JOHN TERMS  AND CONDITIONS:</strong></p>
  Buying on Indy John Terms and Conditions are a part of the Indy John  Terms of Service and apply to all buyers using the Service in addition to the  General Terms and Conditions.<br><p><strong>Purchasing  Merchandise -</strong></p>
  Indy John assists buyers with purchasing merchandise by matching and connecting  with third party suppliers. Buyers submit Buy requests and are matched with  third party suppliers. Indy John doesn't currently handle order processing,  leaving the order processing exclusively to third party suppliers. Suppliers'  listing on the Site constitutes an offer to you to buy their Merchandise. Please  carefully read these Terms and any special terms and conditions including supplier's  returns and refunds policy before placing an order.  We shall not be parties to any contract  between you and the supplier and are not responsible for any act or omission by  either party that may be in violation of such a contract.  Without limiting the foregoing, we are not  responsible for timely performance by either party of its obligations or  failure of any representations or warranties made by either party under such a  contract or for any defects in Merchandise supplied by the suppliers.  If an item of Merchandise is listed at an  incorrect price or with incorrect information due to a typographical error or  error in pricing or product information received from a supplier. We have the  right to refuse or cancel any orders placed for such products or services,  whether or not you have placed the order or have been charged.<br>
<p><strong>Team Purchasing -</strong></p>
  You agree to all Terms and Conditions in this section, as well as all  others not listed in this section. Indy John does allow all users to engage in  team purchasing.  All teams consist of a  Team Manager and Team Members, these team relationships are established when  team managers invite or manually add team members to join their team.  Indy John doesn't have an interest in these  relationships and will not be responsible for ANY disputes resulting from team purchasing  efforts.  Removal from a team is done by  Team Manager which controls ALL team data, details and members.  Payment of user monthly memberships is the  responsibility of the individual users. Team Billing is available as an  option for group paying.<br>
  <p><strong>Descriptions -</strong></p>
  We require the suppliers provided information to be as accurate as  possible.  However, we do not warrant  that Merchandise descriptions or other content on the Site is accurate,  complete, reliable, current or error-free.   If an item of Merchandise offered on the Site is not as described, your  sole remedy is to return it in unused condition. <br>
  <p><strong>Changes to Buy Request -</strong></p>
  Once submitted, any  change(s) to your buy request(s) may be made only by you.  Changes requiring different terms, including  a change in the price and/or time of delivery will be solicited and made by you.   Once buy request is submitted, you may continue,  pause, or delete any request. We reserve the right to cancel any buy request,  in whole or in part, upon your breach of these Terms or your bankruptcy,  insolvency, dissolution, receivership proceedings, or upon the occurrence of  any event leading us to reasonably question your willingness or ability to perform.<br><p><strong>Delivery  Claims and Returns -</strong></p>
  We don't currently handle sale and fulfillment of orders.  We will not be responsible for any disputes  or errors arising during delivery or returning of merchandise.  All orders and details resulting from  buy requests through our service are handled and managed by you and the third  party supplier of merchandise and services. <br><p><strong>Delays  -</strong></p>
  We shall not be liable for  any loss, damage or penalty as a result of any delay in or failure to  manufacture, deliver or otherwise perform hereunder.  If, for reasons  other than force majeure, supplier should default or delay or not deliver the  ordered Merchandise.<br><p><strong>Use of Merchandise -</strong></p>
  The Merchandise offered  through the Service is intended primarily for industrial purposes and, unless  otherwise stated on product labels or in other literature furnished to you by supplier,  is not to be used for any other purposes, including but not limited to, in-vitro  diagnostic purposes, in foods, drugs, medical devices or cosmetics for humans  or animals or for commercial purposes.  You acknowledge that the Merchandise  has not been tested by Indy John for safety and efficacy in food, drug, medical  device, cosmetic, commercial or any other use.  You expressly represent  and warrant to Indy John that you will properly test, use, manufacture and  market any Merchandise purchased through the Service and/or materials produced  with such Merchandise in accordance with the practices of a reasonable person  who is an expert in the field and in strict compliance with all applicable laws  and regulations, now and hereinafter enacted.<br>
<p><strong>Reviews and Endorsements -</strong></p>
  We may use mechanisms that  review and endorse, or allow users to review and endorse, your Merchandise,  Service and your performance as a buyer or general user.  We may make these ratings and feedback  publicly available.<br><p><strong>Patent  Disclaimer -</strong></p>
  We do not warrant that the  use or sale of the Merchandise delivered hereunder will not infringe the claims  of any United States or other patents covering the product itself or the use  thereof in combination with other products or in the operation of any process.</p>
<p><p><strong>IV. Indy John Account Terms:</strong></p>
  <p><strong>Indy John Account  Prices - </strong></p>
  Indy John accounts pricing are non-negotiable and are  subject to change at any time. Prices of committed membership accounts are not  subject to change during the initial commitment period.<br>
<p><strong>Upgrading or  Downgrading an Account -</strong></p>
  You may upgrade your  Indy John account on the Indy John Service. You may also, subject to any  minimum term commitment that may apply, downgrade your Indy John account online  or by contacting Indy John customer service. Such Indy John account changes  will be effective as of the date of your request and your membership will  become subject to the new account you selected. Indy John accounts may be  upgraded or downgraded as follows:<p><strong>Buyer+ Account - </strong></p>
  Free Members can upgrade to Buyer+ Membership account. Upon  any upgrade, Indy John will charge your default payment the fee for the Buyer+  Plan. If your default payment is declined for any reason, Indy John may charge  any credit card on file with your profile. Buyer+ Members cannot upgrade to  another Indy John Buyer Plan.<br>
  <p><strong>Gold and Silver  Membership Accounts -</strong></p>
  Silver Members can upgrade to Gold Membership account. Any  available Credits, that a Silver Member has accumulated will be transferred to  the new upgraded plan in accordance with the rules for the new membership plan.  Upon any upgrade, Indy John will charge your default payment the pro-rated  additional fee for the Gold Membership Plan. If your default payment is  declined for any reason, Indy John may charge any credit card on file with your  profile. Gold Members cannot upgrade to another Indy John Plan.<br>
  <p><strong>Downgrades -</strong></p>
  Buyer+, Gold, and Silver Account users can downgrade to a  free account and any available Credits will be paid to user. Any complimentary  subscription that you receive as part your Buyer+, Gold, or Silver Membership  accounts will expire upon any downgrade to the free account.<br>
  <p><strong>Team Billing -</strong></p>
  Any user or team manager may pay for all team member  accounts; this billing is treated as any other account purchase and covered by  all terms and conditions regarding billing. Indy John will not responsible for  any disputes related to billing, as this dispute is solely between Team Manager  and Team Member.<br>
  <p><strong>Annual payment option  -</strong></p>
  Indy John offers annual subscriptions with discounted  pricing - this pricing and discounted rate is non-negotiable and available to  all users. Indy John has the right to change discounting rates and pricing  terms at any time.  Team billing terms  also applies to annual payment subscriptions.   No refund will be issued for members who decide to end relationship with  their team. <br>
  <p><strong>Cancellation of Indy  John Accounts -</strong></p>
  You may cancel your Indy John account online, by contacting  Indy John customer service, or by simply not using the Indy John service. Upon  cancellation of any membership, all available credits will expire, and all  complimentary Subscriptions will expire. Members will not receive a full or  partial refund of any monthly or annual fee already paid.</p>
<p><p><strong>V.   INDY JOHN REFERRAL PROGRAM TERMS:</strong></p>
  <p><strong>General -</strong></p>
  These terms and conditions as  well as all other Indy John general terms apply to Indy John's Referral Program  ("Program"). By referring a friend, purchasing valued accounts, or otherwise  participating in the Program, the referring customer and referred friend agree  to be bound by these terms and conditions, Indy John's General Terms and  Conditions, and the Indy John's Privacy Policy.   You agree to a mandatory arbitration provision that provides that  (except for matters properly brought to small claims court) any claim,  controversy, or dispute of any kind between you and Indy John must be resolved  by final and binding arbitration on an individual and not a class-wide or  consolidated basis.<br>
  <p><strong>Program  Participation and Eligibility -</strong></p>
  The Program is available  only to Indy John users signed up to use Indy John services. Referral payout  will be paid to any user that refers another user signed up for a valued  account. Please allow up to 45 days after referral validation for referral  reward to be applied electronically or by check, payouts are available via  check upon request. Indy John reserves the right to modify, extend or cancel  this Program at any time. The Program is only available online through the Indy  John website. Internet access is required for participation in the Program.  Current Indy John customers, who initiate a referral, are defined as  "Referrers." Non-customers who sign up for Indy John service upon a referral  are defined as "Referees."<br>
  <p><strong>Eligible Referrals - </strong></p>
  The Program is only  available for active Indy John users in good standing. To make referrals, you  must have signed up for Indy John services and be an individual person of the  age of majority in the state/province or jurisdiction where you are resident at  the time of participation.<br>
  Participation in the Program  is prohibited where void by applicable law or regulation. The Program is only  available through IndyJohn.com. If your account is "interrupted", "suspended"  or you cancel your account with Indy John, you are no longer eligible to  participate in the Program. Upon cancellation with Indy John, your account will  be inactive and you may not make referrals or earn Program payouts, including  any referral credits that may be pending. You cannot redeem a referral credit  for referring yourself. You may only participate in the program online at IndyJohn.com,  not at any retail outlet. You may only participate in the Program with one  account. People you invite ("Referees") have to activate a new valued monthly  account for you to receive a referral payout. To participate and earn a payout,  Referees must register on the Indy John website, sign up for a valued account  and generate a service activation date.<br>
  <p><strong>Ineligible Referrals - </strong></p>
  Unless otherwise noted, this  program applies only to Buyer+ and Silver and Gold accounts.  The Program may not be available for other Indy  John accounts or services, and other plans deemed ineligible (collectively,  "Ineligible Referrals"). In addition, Referrals made through non-authorized Indy  John referral channels are not eligible for the program. Indy John reserves the  right to void any Referral credit based on the following: (1) ineligibility of  any Program participant, (2) fraudulent activation or, (3) if Indy John, in its  sole discretion, finds that you have violated any of the Program Terms and  Conditions.<br>
<p><strong>Eligible Referees -</strong></p>
  Each Referee must activate a  new Indy John valued monthly account for referral payout to take place.  You cannot receive credits for referring  yourself or by renewing your monthly plan with Indy John. There is no maximum  on how much Indy John users can earn in a calendar year. If you are a new Indy  John customer who was referred by an existing Indy John customer, you are  eligible to earn referral rewards, including your initial referral reward. You  must disclose the fact that you are an Indy John customer when you make  referrals. You agree to let your Referees know that you are the Referrer and  that you may receive a referral reward if your Referee signs up for Indy John  service. You will not receive any referral reward if your referrals are  rejected or are not received for any reason, or if you fail to comply with any  of the terms of the Program.<br>
  <p><strong>Reward Redemption -</strong></p>
  Referral rewards are  non-transferable, non-assignable, and cannot be redeemed or exchanged for cash,  credit, or other merchandise.<br>
  <p><strong>Reward Issuance Expiration -</strong></p>
  If further action is  required for reward issuance, members successfully complete the additional  action within 30 days from initial notification of the request for further action;  otherwise the member will forfeit the pending reward.<br>
  <p><strong> Referral Program Tax and  Liability -</strong></p>
  You are responsible for any  and all tax liabilities associated with the Program.  Contact your tax professional to learn about  referral payout tax responsibilities.<br>

  <p><strong>Void Where Prohibited -</strong></p>
  This Program is void where  prohibited by law.<br>
<p><strong>Changes to the Program -</strong></p>
  <p>We reserve the right to  change the terms and conditions of the Indy John Referral Program at any time,  without notice, at our sole discretion. We reserve the right to not award a  credit or disqualify someone from the Program if we feel, in our sole  discretion, that fraudulent behavior or other unethical conduct has occurred in  any way that compromises the fairness the Program in any way. Credits cannot be  combined with other promotions and are not valid for previous offers or orders.  Spam, unsolicited commercial email, or any form of illegal means of  communication is illegal, prohibited, and will be grounds for termination of  your account and participation in this Program. Fraudulent or unethical means  of communication such as using bots, fictitious identities, fake emails, or  scripts is also prohibited and will result in similar actions by us with  respect to terminating your account and participation in the Program. <br>
  </p>
  <p>By participating in this  Program, you agree to release and hold us harmless from any and all claims or  damages arising out of, or in connection with the Program. You further agree  that the Program and credits are provided "as is where is". THERE ARE  NO REPRESENTATIONS OR WARRANTIES INCLUDING BUT NOT LIMITED TO STATUTORY  WARRANTIES AND CONDITIONS, WARRANTIES AND CONDITIONS OF MERCHANTABILITY,  FITNESS FOR A PARTICULAR PURPOSE, THIRD PARTIES RIGHTS, AND NON-INFRINGEMENT OF  PROPRIETARY RIGHTS. IN NO EVENT WILL EITHER PARTY BE LIABLE TO THE OTHER FOR  ANY CONSEQUENTIAL, INCIDENTAL, OR SPECIAL DAMAGES, INCLUDING ANY LOST PROFITS  OR LOST SAVINGS, EVEN IF ONE PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH  DAMAGES, OR FOR ANY CLAIM BY ANY THIRD PARTY. </p>
  </p>
  <p><p><strong> </strong><strong>VI. INDY JOHN JOB BOARD TERMS:</strong></p>
  Prior to using our job board service, you agree to all the  following rules and terms, as well as all other terms of usage covered by our  general terms and conditions and privacy policies. This job listing feature and  service on the Indy John platform connects Job seekers or Candidates with  Employers.  Candidates can apply directly  to Job Poster via Indy John platform. We do not employ job seekers or  Candidates, and it's entirely up to Employers to engage with prospects and  offer the listed job. Job Postings or Listings are valid for 30 days unless  you're a valued account holder, meaning a non-free account user, for which they  do not expire. Job Posting fee is non-refundable and non-negotiable, rates may  change without prior notice, and all rate changes are decided by Indy John,  Inc.<br>
  <br>
While using our Job posting or listing service, you agree  not to do any of the following without our prior written consent -<br>
  <br>
Post any job related information with any inaccurate,  incomplete, or misleading information.<br>
  <br>
Create other job postings as your own, post the same listing  more than once on the Site or post multiple listings within one posting using  external code or scripts.<br>
  <br>
Promote other job listing service providers by placing any  content within the job details of a job posting that directs Indy John users  seeking jobs to apply directly via another job posting or listing service  provider.<br>
  <br>
Resell job listing information or make this information  available to any person who is a professional who assists job seekers with all related  employment assistance.<br>
  <br>
Use any software to navigate, search or store information from the Indy  John site. As well as modify any portion of the Site.<br>
  <br>
Express that any statements or interaction you make are  endorsed by us.<br>
  Impersonate any person or entity.<br>
  <br>
Respond to a job listing on behalf of anyone other than  yourself.<br>
  <br>
Delete or revise any material posted by any other person or  entity.<br>
  <br>
Restrict or inhibit any other user from using and enjoying  the Site and services, including, without limitation, by means of  "hacking" or defacing any portion of the Site.<br>
  <br>
Post or transmit any job advertisement or posting that does  not comply with applicable law, including, but not limited to, United States  federal, state and local laws relating to equal employment opportunity and  employment eligibility verification; including post or transmit any job  advertisement or posting that require a visa as a condition of employment; or  that require United States citizenship or lawful permanent residence in the  United States as a condition of employment, except when necessary to comply  with law, regulation, executive order, or government contract.
  </p>
<p>Remove any copyright, trademark, or other proprietary rights  notices contained in the Site.Indy John assumes no responsibility or liability  for any person(s) selected by your company. Selection is based solely on your  company's investigation, verification and determination that such hire is  suitable for your company's purposes.<br>
  <br>
The Company has no obligation to monitor any of Indy John's  services. However, you acknowledge and agree that Indy John has the right at any  time to monitor all services provided by this platform, including any user  interaction, and the materials you transmit or post, to protect itself, its  sponsors, its registered users and visitors, and to comply with legal  obligations or governmental requests. Indy John reserves the right to refuse to  post or to remove any information or materials, in whole or in part, that it  deems in its sole discretion to be unacceptable, offensive or in violation of  this Agreement. The Company also reserves the right to prohibit any user who  violates any or all Terms of Conditions or Privacy Policy.</p>




<div class="clearfix"></div>

                </div>
<div class="clearfix"></div>
            </div>
<div class="clearfix"></div>
        </section>

<!--=======================================================-->

@include('home.footerlinks')
@endsection
